client_config_backend: settings
client_config:
  client_id: 879134268663-6fr4o4aimhebdt0uvokv9daseg6l06bb.apps.googleusercontent.com
  client_secret: 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1

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install